name: Build and Deploy code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2

      - name: Install python version 3.11.5
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.5"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -r Socail_media.requirements.txt