name : Build and Deploy code.

on: [push, pull_request]

jobs :
  job1:
    runs-on : ubuntu-latest
    steps : 
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to suraj 
        run: echo "hii Suraj....."
      - name: Install python version 3.11.5
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.5"
      - name: Upgrade pip
        uses: python -m pip install --upgrade pip
      - name: Install Dependencies
        uses: pip install -r Socail_media.requirements.txt